name: Branch Synchronization

on:
  push:
    branches:
      - dev
      - stable

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Prepare sync branch
        id: branch
        run: |
          echo "SYNC_BRANCH_DEV_CANARY=sync/dev-to-canary-$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "SYNC_BRANCH_STABLE_DEV=sync/stable-to-dev-$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "SYNC_BRANCH_STABLE_CANARY=sync/stable-to-canary-$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Sync dev to canary
        if: github.ref == 'refs/heads/dev'
        run: |
          git checkout dev
          git checkout -B ${{ env.SYNC_BRANCH_DEV_CANARY }}
          git push origin ${{ env.SYNC_BRANCH_DEV_CANARY }} -f
          gh pr create --base canary --head ${{ env.SYNC_BRANCH_DEV_CANARY }} --title "Sync dev branch to canary branch" --body "Automatic sync" || exit 0

        env:
          GH_TOKEN: ${{ github.token }}

      - name: Sync stable to dev and canary
        if: github.ref == 'refs/heads/stable'
        run: |
          # Sync stable to dev
          git checkout stable
          SYNC_BRANCH_DEV=${{ env.SYNC_BRANCH_STABLE_DEV }}
          git checkout -B $SYNC_BRANCH_DEV
          git push origin $SYNC_BRANCH_DEV -f
          gh pr create --base dev --head $SYNC_BRANCH_DEV --title "Sync stable branch to dev branch" --body "Automatic sync" || exit 0

          # # Sync stable to canary
          # git checkout stable
          # SYNC_BRANCH_CANARY=${{ env.SYNC_BRANCH_STABLE_CANARY }}
          # git checkout -B $SYNC_BRANCH_CANARY
          # git push origin $SYNC_BRANCH_CANARY -f
          # gh pr create --base canary --head $SYNC_BRANCH_CANARY --title "Sync stable branch to canary branch" --body "Automatic sync" || exit 0

        env:
          GH_TOKEN: ${{ github.token }}
